mezmeds/home/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^|home$', views.home, name='home_index'),
    # url(r'^posttodo/$', views.post_todo, name='post_todo'),
    # url(r'^gettodo/$', views.todo_all, name='todo_all'),
]

mezmeds/mezmeds/urls.py
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', include('home.urls'), name='home'),
    url(r'^stockman/', include('stockman.urls', namespace='stockman')),
    url(r'^stockstats/', include('stockstats.urls', namespace='stockstats')),

    url(r'^dropdowns/', include('dropdowns.urls', namespace='dropdowns')),
]

mezmeds/stockman/urls.py
from django.conf.urls import url, include

from . import views
urlpatterns = [

    #SITE

    url(r'^stockman/$', views.index, name='stockman'),
    url(r'^clinicorders/$', views.indexOrder, name='clinicorders'),
    url(r'^dilivery/$', views.indexDeliveries, name='dilivery'),

    # AJAX

    url(r'^clinicdata/$', views.get_clinic_data, name='clinicdata'),
    url(r'^newstockdata/$', views.post_stock_level, name='newstockdata'),
    url(r'^clinicrestocklist/$', views.get_restock_stock_level, name='clinicrestocklist'),
    url(r'^clinicorderspost/$', views.post_order_stock, name='clinicorderspost'),
    url(r'^diliverylist/$', views.dilivery_list, name='diliverylist'),
    url(r'^diliveryrecieved/$', views.dilivery_recieved, name='diliveryrecieved'),


]

mezmeds/stockstats/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^bargraph/$', views.get_graph_data, name='bargraph'),

]

mezmeds/templates/base.html
{% load staticfiles %}


<html lang="en">
<head>
  <meta charset="utf-8">

  <title></title>

  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->

{% include "common_javascript.html" %}
{% include "common_css.html" %}
</head>

<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

</body>
</html>

mezmeds/templates/common_css.html
{% load staticfiles %}

<!-- Bootstrap css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- fontawesome -->

    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<!-- Chosen -->

    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.css" rel="stylesheet">

<!-- custome css -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

mezmeds/templates/common_javascript.html
<!-- Javascript which is used on all pages/ site wide -->

{% load static %}

<!-- jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- Bootstrap -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<!-- font awesome  -->
<script src="https://use.fontawesome.com/9b3a17146c.js"></script>


<!-- Chosen  -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.6.2/chosen.jquery.js"></script>

<!-- Jquery plugin -->

mezmeds/templates/navbar.html
{% load staticfiles %}

<!-- This markup was taken from an older project of mine and is not new code, I do not know the full details of all the bootstrap classes here -->

 <!-- Static navbar -->
  <nav class="navbar navbar-default navbar-static-top ">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed glyphicon glyphicon-list" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
        </button>
        <a class="navbar-brand nav-center" href="/"></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">

        <ul class="nav navbar-nav">

         <button type="button" class="btn btn-default"><li><a class="navbar-brand" href="/">Home</a></li></button>

        </ul>

        <ul class="nav navbar-nav">

          <button type="button" class="btn btn-default"><li><a class="navbar-brand" href="{% url 'stockman:stockman'%}">Stock Management</a></li></button>

        </ul>

        <ul class="nav navbar-nav">

               <button type="button" class="btn btn-default"><li><a class="navbar-brand" href="{% url 'stockstats:index'%}">Clinic Statistics</a></li></button>

        </ul>

        <ul class="nav navbar-nav">

          <button type="button" class="btn btn-default"><li><a class="navbar-brand" href="{% url 'stockman:clinicorders'%}">Clinic Restock</a></li></button>

        </ul>

        <ul class="nav navbar-nav navbar-right" style="margin-top: 15px">

          <button type="button" class="btn btn-success btn-lg btn-block">
               <a  href="{% url 'stockman:dilivery'%}"><i class="icon-truck icon-large icon-light"> Orders/Deliveries </i></a>
          </button>

        </ul>

     </div><!--/.nav-collapse -->
    </div>
  </nav>